Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Location.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria_static.Models
{
    [Table("locations")]
    public class Location
    {
        [Key]
        public int LocationId { get; set; }
        [Required]
        public string Name { get; set; }
        public string ImgPath { get; set; }
        public string State { get; set; }
    }
}

Models/Pizza.cs
using la_mia_pizzeria_static.Validators;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria_static.Models
{
    [Table("pizzas")]
    public class Pizza
    {
        public Pizza()
        {
    
        }

        [Key]
        public int PizzaId { get; set; }
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [StringLength(25, ErrorMessage = "Il nome non può avere più di 25 caratteri")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [FiveWordsValidationAttribute]
        [Column(TypeName = "text")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [Url]
        public string ImgPath { get; set; }
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        public string Price { get; set; }
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LocationsController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class LocationsController : Controller
    {
        // GET: LocationsController
        public ActionResult Index()
        {
            using (PizzeriaContext db = new PizzeriaContext())
            {
                List<Location> locationsList = db.Locations.ToList<Location>();
                return View(locationsList);
            }
        }

        // GET: LocationsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LocationsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LocationsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LocationsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LocationsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LocationsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LocationsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/PizzeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzeController : Controller
    {
        public IActionResult Index()
        {
            using (PizzeriaContext db = new PizzeriaContext())
            {
                List<Pizza> pizzaList = db.Pizzas.ToList<Pizza>();
                return View(pizzaList);
            }
        }

        [Route("/menu")]
        public IActionResult Details(int id)
        {
            using (PizzeriaContext db = new PizzeriaContext())
            {
                Pizza current = db.Pizzas.Find(id);

                if (current == null)
                {
                    return NotFound($"La pizza con id {id} non è stato trovato");
                }
                else
                {
                    return View(current);
                }
            }

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Pizza pizza)
        {   
            if (!ModelState.IsValid)
            {
                return View("Create", pizza);
            } else
            {
                PizzeriaContext db = new PizzeriaContext();
                db.Pizzas.Add(pizza);
                db.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

Views/Locations/Index.cshtml
@{
	ViewData["Title"] = "Dove siamo";
}

@model List<Location>

@{
	List<string> states = new List<string>();
	foreach (Location location in Model)
	{
		if (!states.Contains(location.State))
			states.Add(location.State);
	}
}

<div class="container text-center">
	<h1>Locations</h1>
	@if (Model.Count() == 0)
	{
		<div class="w-100">Non ci sono locations nella lista</div>
	}
	else
	{
		@foreach (string state in states)
		{
			<section class="text-start">
				<h2>@state</h2>
				<div class="row row-cols-3 gy-3">
					@foreach (Location location in Model.Where(e => e.State == state))
					{
						<div class="col">
							<div class="card text-center">
								<h5 class="card-title">@location.Name</h5>
								<img src="@location.ImgPath" class="card-img-top" alt="location">
							</div>
						</div>
					}
				</div>
			</section>
		}
	}
</div>

Views/Pizze/Create.cshtml
@{
	ViewData["Title"] = "Add a new pizza";
}

@model Pizza

<div class="container">
	<h1 class="mb-3">Aggiungi una nuova pizza</h1>
	<form asp-controller="Pizze" asp-action="Create" method="post">
		@Html.AntiForgeryToken()
		<div class="mb-3">
			<label for="pizza-name" class="form-label">Name</label>
			<input type="text" asp-for="Name" class="form-control" id="pizza-name">
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label for="pizza-description" class="form-label">Descrizione</label>
			<textarea id="pizza-description" class="form-control" asp-for="Description"></textarea>
			<span asp-validation-for="Description" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label for="img-path" class="form-label">Image Path</label>
			<input type="url" class="form-control" id="img-path" asp-for="ImgPath">
			<span asp-validation-for="ImgPath" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label for="price" class="form-label">Prezzo</label>
			<input type="text" class="form-control" id="price" asp-for="Price">
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>

Views/Pizze/Details.cshtml
@model Pizza

@{
	ViewData["Title"] = @Model.Name;
}

<div class="container">
	<h2>@Model.Name</h2>
	<img src="@Model.ImgPath"/>
	<div>@Model.Price</div>
	<p>@Model.Description</p>
</div>

Views/Pizze/Index.cshtml
@{
	ViewData["Title"] = "Menu";
}

@model List<Pizza>

<div class="container text-center">
	<h1 class="display-4">Menu</h1>
	<p>In GTA San Andreas, the player is given a choice of four different meals at Well Stacked Pizza restaurants. All of the food choices besides the salad are references to breasts: "Buster" is from the word "bust", a word for breasts, or it could be a reference to Ryder's catchphrase. "Double D-Luxe" is from DD, the bra size, and having a "Full Rack" is slang for a woman with large, well-shaped breasts. In Las Venturas, the pricing of the Double D-Luxe, Full Rack and Salad Meal are 20% higher than in the rest of the state.</p>
	@if (Model.Count() == 0)
	{
		<div class="w-100">Non ci sono pizze nella lista</div>
	}
	else
	{
		<div class="row row-cols-3 gy-3">
			@foreach (Pizza pizza in Model)
			{
				<div class="col">
					<div class="card">
						<div class="card-body">
							<a href="@Url.Action("details","pizze", new {id = pizza.PizzaId})">
								<h5 class="card-title">@pizza.Name</h5>
							</a>
							<p class="card-text">@pizza.Description</p>
						</div>
						<img src="@pizza.ImgPath" class="card-img-top" alt="pizza">
						<div class="card-text">@pizza.Price</div>
					</div>
				</div>
			}
		</div>
	}
	<a class="btn btn-primary mt-3" asp-controller="Pizze" asp-action="Create">Aggiungi una nuova pizza</a>
</div>

Views/Shared/_Footer.cshtml
<div class="container">
	&copy; 2022 - The Well Stacked Pizza Co. - <a asp-area="" asp-controller="Locations" asp-action="Index">Dove siamo</a> - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
</div>

Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
	<div class="container-fluid">
		<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/logo.png" /></a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
				aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
			<ul class="navbar-nav flex-grow-1">
				<li class="nav-item">
					<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" asp-area="" asp-controller="Pizze" asp-action="Index">Menu</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="Index">Dove siamo</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
				</li>
			</ul>
		</div>
	</div>
</nav>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - The Well Stacked Pizza Co.</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		@Html.Partial("_Header")
	</header>

	<main role="main" class="p-3">
		@RenderBody()
	</main>

	<footer class="border-top footer text-muted">
		@Html.Partial("_Footer")
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>